# Generated by Django 2.2 on 2022-07-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220717_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passed_tests',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во пройденых тестов'),
        ),
    ]
